package com.kma.quiz_game.ui.game.art

/**
 * Where every sprite lives inside the two pages the arena loads.
 *
 * Generated by `tools/battle-art/build_battle_art.py` and checked in rather than read from a
 * manifest at runtime: the numbers change only when the artwork does, and a table the compiler can
 * see beats a file the renderer has to parse on the GL thread before it can draw a frame.
 *
 * Plain data on purpose -- no libGDX types -- so the lookup that matters (which sprite for which
 * `art_code`, and what to do when there isn't one) can be tested without a GL context.
 */
object BattleArt {

    const val HERO_PAGE = "battle/hero.png"
    const val MONSTER_PAGE = "battle/monsters.png"
    const val BACKDROP = "battle/backdrop.png"

    /** The hero page is a plain grid; every frame is cropped to the same box around the same feet. */
    const val HERO_COLUMNS = 8
    const val HERO_FRAME_WIDTH = 81
    const val HERO_FRAME_HEIGHT = 50

    /** Where the ground is inside a frame, in frame pixels from its top. */
    const val HERO_FEET = 50

    /**
     * Where the knight himself is inside that frame, as a fraction of its width.
     *
     * The frame is much wider than he is, because an attack throws his sword across it and every
     * frame shares one box. Without these two the arena would centre the box instead of the man,
     * and he would appear to slide sideways the moment he swung.
     */
    const val HERO_BODY_CENTRE = 0.284f
    const val HERO_BODY_HALF_WIDTH = 0.284f

    /** Where he is once the frame is flipped, for the knight who faces the other way. */
    const val HERO_BODY_CENTRE_MIRRORED = 1f - HERO_BODY_CENTRE

    /**
     * One entry per catalog `art_code`.
     *
     * The `_KING`/`_CHIEF`/`ALPHA_`/`STONE_` tiers get their own tile rather than a tinted copy of
     * the base creature: the CC0 set had a bigger cousin for every one of them, and a hobgoblin
     * reads as a promoted goblin in a way a larger goblin does not.
     */
    val MONSTERS: Map<String, MonsterArt> = mapOf(
        "SLIME" to MonsterArt(1, 53, 64, 44, 74f),
        "SLIME_KING" to MonsterArt(66, 1, 64, 96, 92f),
        "GOBLIN" to MonsterArt(131, 45, 50, 52, 88f),
        "GOBLIN_CHIEF" to MonsterArt(182, 35, 60, 62, 98f),
        "DIRE_WOLF" to MonsterArt(243, 35, 62, 62, 74f),
        "ALPHA_WOLF" to MonsterArt(306, 33, 64, 64, 84f),
        "GOLEM" to MonsterArt(371, 35, 62, 62, 100f),
        "STONE_TITAN" to MonsterArt(434, 35, 62, 62, 112f),
        "WRAITH" to MonsterArt(497, 35, 56, 62, 92f),
        "LICH" to MonsterArt(554, 33, 58, 64, 96f),
        "DRAKE" to MonsterArt(613, 33, 64, 64, 96f),
        "DRAGON" to MonsterArt(678, 33, 64, 64, 116f),
    )

    /**
     * The sprite for a code, or null for one the catalog grew after this page was packed.
     *
     * A null is not a failure: the arena falls back to the drawn silhouette it used before there
     * were any sprites at all, so a monster added server-side still shows up in a fight instead of
     * leaving an empty stage.
     */
    fun monster(artCode: String): MonsterArt? = MONSTERS[artCode]
}

/**
 * One creature on the monster page.
 *
 * [worldHeight] is how tall it stands in the arena's own units, not how tall the tile is: the
 * tiles are all roughly 32 pixels square, and drawing a slime and a dragon at the same height
 * would throw away the only sense of scale the fight has.
 */
data class MonsterArt(
    val x: Int,
    val y: Int,
    val width: Int,
    val height: Int,
    val worldHeight: Float,
)

/**
 * A run of frames on the hero page, with the frame rate TurnBasedBattle's own `.anim` file gives
 * it -- so the knight idles, swings and flinches at exactly the speed he does in the Unity game.
 */
enum class HeroClip(val start: Int, val count: Int, val fps: Float, val looping: Boolean) {
    IDLE(start = 0, count = 8, fps = 8f, looping = true),
    ATTACK(start = 8, count = 6, fps = 14f, looping = false),
    HURT(start = 14, count = 3, fps = 11f, looping = false),

    /** The guard flourish, borrowed for a skill cast: the one beat the knight does something else. */
    CAST(start = 17, count = 5, fps = 12f, looping = false);

    val seconds: Float get() = count / fps

    /** Which frame of this clip is showing [elapsed] seconds in. A clip that has run out holds. */
    fun frameAt(elapsed: Float): Int {
        val step = (elapsed * fps).toInt()
        val index = if (looping) step % count else step.coerceAtMost(count - 1)
        return start + index
    }
}
