package com.kma.quiz_game.ui.game.art

/**
 * Where every sprite lives inside the two pages the arena loads.
 *
 * Generated by `tools/battle-art/build_battle_art.py` and checked in rather than read from a
 * manifest at runtime: the numbers change only when the artwork does, and a table the compiler can
 * see beats a file the renderer has to parse on the GL thread before it can draw a frame.
 *
 * Plain data on purpose -- no libGDX types -- so the lookup that matters (which sprite for which
 * `art_code`, and what to do when there isn't one) can be tested without a GL context.
 */
object BattleArt {

    /** The archer's arrow, the one projectile with artwork of its own. A spell is drawn, not cut. */
    const val ARROW = "battle/arrow.png"

    const val MONSTER_PAGE = "battle/monsters.png"
    const val BACKDROP = "battle/backdrop.png"

    /**
     * One page per school, each with the grid and clip timings of the pack it came from.
     *
     * Deliberately not one shared grid. The three packs are drawn at different resolutions, and
     * forcing them onto a common frame size would mean resampling pixel art -- so each keeps its
     * own frame box and the arena scales it on screen instead (see [HeroArt.bodyHeight]).
     *
     * Generated by `tools/battle-art/build_battle_art.py`; paste its output over this map.
     */
    val HEROES: Map<String, HeroArt> = mapOf(
        "WARRIOR" to HeroArt(
            page = "battle/hero.png",
            columns = 8, frameWidth = 81, frameHeight = 50,
            feet = 50, bodyHeight = 40,
            bodyCentre = 0.284f, bodyHalfWidth = 0.284f,
            clips = mapOf(
                HeroClip.IDLE to Clip(0, 8, 8.0f, looping = true),
                HeroClip.ATTACK to Clip(8, 6, 14.0f),
                HeroClip.HURT to Clip(14, 3, 11.0f),
                HeroClip.CAST to Clip(17, 5, 12.0f),
            ),
        ),
        "MAGE" to HeroArt(
            page = "battle/hero_mage.png",
            columns = 8, frameWidth = 93, frameHeight = 68,
            feet = 68, bodyHeight = 43,
            bodyCentre = 0.3548f, bodyHalfWidth = 0.1505f,
            clips = mapOf(
                HeroClip.IDLE to Clip(0, 6, 8.0f, looping = true),
                HeroClip.ATTACK to Clip(6, 8, 14.0f),
                HeroClip.HURT to Clip(14, 4, 11.0f),
                HeroClip.CAST to Clip(18, 8, 12.0f),
            ),
            attack = AttackStyle.SPELL,
        ),
        "ARCHER" to HeroArt(
            page = "battle/hero_archer.png",
            columns = 8, frameWidth = 46, frameHeight = 45,
            feet = 45, bodyHeight = 36,
            bodyCentre = 0.3478f, bodyHalfWidth = 0.3478f,
            clips = mapOf(
                HeroClip.IDLE to Clip(0, 10, 8.0f, looping = true),
                HeroClip.ATTACK to Clip(10, 6, 14.0f),
                HeroClip.HURT to Clip(16, 3, 11.0f),
                // Huntress 2 animates one attack, so drawing the bow is what casting looks like.
                HeroClip.CAST to Clip(19, 6, 12.0f),
            ),
            attack = AttackStyle.ARROW,
        ),
    )

    /** The school a player with no class yet fights as, and the fallback for an unknown code. */
    val DEFAULT_HERO: HeroArt = HEROES.getValue("WARRIOR")

    /** A costume: which school it belongs to, and the page to draw that school from while worn. */
    private data class Costume(val school: String, val page: String)

    /**
     * Every costume the shop sells, by item code.
     *
     * A costume belongs to one school, because it is that school's own page with its garment hues
     * rotated -- there is no way to put the knight's tabard on the archer.
     *
     * Nothing stops a player buying and wearing another school's costume today: the shop does not
     * filter by class and `wear_skin` only checks ownership. So this falls back to the school's
     * own page rather than drawing the wrong character -- a costume that does nothing is a poor
     * purchase, but a mage who turns into a recoloured knight mid-match is a bug.
     */
    private val COSTUMES: Map<String, Costume> = mapOf(
        "SKIN_ROOKIE" to Costume("WARRIOR", "battle/hero_rookie.png"),
        "SKIN_SCHOLAR" to Costume("WARRIOR", "battle/hero_scholar.png"),
        "SKIN_OFFICE" to Costume("WARRIOR", "battle/hero_office.png"),
        "SKIN_NIGHT" to Costume("WARRIOR", "battle/hero_night.png"),
        "SKIN_ORATOR" to Costume("WARRIOR", "battle/hero_orator.png"),
        "SKIN_LAUREATE" to Costume("WARRIOR", "battle/hero_laureate.png"),
        "SKIN_MAGE_INK" to Costume("MAGE", "battle/hero_mage_ink.png"),
        "SKIN_MAGE_EMBER" to Costume("MAGE", "battle/hero_mage_ember.png"),
        "SKIN_MAGE_JADE" to Costume("MAGE", "battle/hero_mage_jade.png"),
        "SKIN_ARCHER_DUSK" to Costume("ARCHER", "battle/hero_archer_dusk.png"),
        "SKIN_ARCHER_AZURE" to Costume("ARCHER", "battle/hero_archer_azure.png"),
        "SKIN_ARCHER_PLUM" to Costume("ARCHER", "battle/hero_archer_plum.png"),
    )

    /**
     * Which school a server `class_code` draws as.
     *
     * `ASSASSIN` is the code the archer still answers to: the school has been renamed twice
     * without the code ever moving, so this is the only place that has to know.
     */
    private fun schoolFor(classCode: String?): String = when (classCode?.uppercase()) {
        "MAGE" -> "MAGE"
        "ASSASSIN", "ARCHER", "SCHOLAR" -> "ARCHER"
        else -> "WARRIOR"
    }

    /** The artwork for one fighter: their school, wearing their costume. */
    fun heroFor(classCode: String?, skinCode: String? = null): HeroArt {
        val school = schoolFor(classCode)
        val art = HEROES[school] ?: DEFAULT_HERO
        val costume = COSTUMES[skinCode?.uppercase()] ?: return art
        return if (costume.school == school) art.copy(page = costume.page) else art
    }

    /**
     * One entry per catalog `art_code`.
     *
     * The `_KING`/`_CHIEF`/`ALPHA_`/`STONE_` tiers get their own tile rather than a tinted copy of
     * the base creature: the CC0 set had a bigger cousin for every one of them, and a hobgoblin
     * reads as a promoted goblin in a way a larger goblin does not.
     */
    val MONSTERS: Map<String, MonsterArt> = mapOf(
        "SLIME" to MonsterArt(1, 53, 64, 44, 74f),
        "SLIME_KING" to MonsterArt(66, 1, 64, 96, 92f),
        "GOBLIN" to MonsterArt(131, 45, 50, 52, 88f),
        "GOBLIN_CHIEF" to MonsterArt(182, 35, 60, 62, 98f),
        "DIRE_WOLF" to MonsterArt(243, 35, 62, 62, 74f),
        "ALPHA_WOLF" to MonsterArt(306, 33, 64, 64, 84f),
        "GOLEM" to MonsterArt(371, 35, 62, 62, 100f),
        "STONE_TITAN" to MonsterArt(434, 35, 62, 62, 112f),
        "WRAITH" to MonsterArt(497, 35, 56, 62, 92f),
        "LICH" to MonsterArt(554, 33, 58, 64, 96f),
        "DRAKE" to MonsterArt(613, 33, 64, 64, 96f),
        "DRAGON" to MonsterArt(678, 33, 64, 64, 116f),
    )

    /**
     * The sprite for a code, or null for one the catalog grew after this page was packed.
     *
     * A null is not a failure: the arena falls back to the drawn silhouette it used before there
     * were any sprites at all, so a monster added server-side still shows up in a fight instead of
     * leaving an empty stage.
     */
    fun monster(artCode: String): MonsterArt? = MONSTERS[artCode]
}

/**
 * One creature on the monster page.
 *
 * [worldHeight] is how tall it stands in the arena's own units, not how tall the tile is: the
 * tiles are all roughly 32 pixels square, and drawing a slime and a dragon at the same height
 * would throw away the only sense of scale the fight has.
 */
data class MonsterArt(
    val x: Int,
    val y: Int,
    val width: Int,
    val height: Int,
    val worldHeight: Float,
)

/**
 * What a fighter is doing. Which frames that is depends on their school -- see [HeroArt.clips].
 */
enum class HeroClip { IDLE, ATTACK, HURT, CAST }

/**
 * How a school reaches its opponent.
 *
 * [MELEE] closes the distance: the fighter slides across the stage, strikes, and comes back. That
 * is the only style the arena had while everyone was a knight.
 *
 * The other two stay home and send something instead, because a mage who runs the length of the
 * stage to wave a staff -- or an archer who does it holding a drawn bow -- reads as a bug, not as
 * an attack. The projectile crosses in exactly the time the lunge used to take, so when the blow
 * lands is unchanged and nothing above the renderer has to know which style a fighter uses.
 */
enum class AttackStyle { MELEE, ARROW, SPELL }

/** A run of frames on a hero page, at the frame rate its own pack animates it. */
data class Clip(
    val start: Int,
    val count: Int,
    val fps: Float,
    val looping: Boolean = false,
) {
    val seconds: Float get() = count / fps

    /** Which frame of this clip is showing [elapsed] seconds in. A clip that has run out holds. */
    fun frameAt(elapsed: Float): Int {
        val step = (elapsed * fps).toInt()
        val index = if (looping) step % count else step.coerceAtMost(count - 1)
        return start + index
    }
}

/**
 * One school's page: its grid, where the fighter stands inside a frame, and its four clips.
 *
 * [bodyHeight] is what makes three packs drawn at three resolutions stand the same height on one
 * stage. The arena scales a frame so that [bodyHeight] -- the fighter himself, not the box around
 * him -- comes out at a fixed number of world units, so a pack that draws taller sprites does not
 * produce a taller fighter.
 *
 * [bodyCentre] and [bodyHalfWidth] are fractions of [frameWidth]. The box is wider than the
 * fighter, because an attack throws a sword or a spell across it and every frame shares one box;
 * without these the arena would centre the box rather than the man, and he would slide sideways
 * the moment he swung.
 */
data class HeroArt(
    val page: String,
    val columns: Int,
    val frameWidth: Int,
    val frameHeight: Int,
    /** Where the ground is inside a frame, in frame pixels from its top. */
    val feet: Int,
    /** How tall the fighter himself is, in frame pixels, standing idle. */
    val bodyHeight: Int,
    val bodyCentre: Float,
    val bodyHalfWidth: Float,
    val clips: Map<HeroClip, Clip>,
    val attack: AttackStyle = AttackStyle.MELEE,
) {
    val isRanged: Boolean get() = attack != AttackStyle.MELEE

    /** Where he is once the frame is flipped, for the fighter who faces the other way. */
    val bodyCentreMirrored: Float get() = 1f - bodyCentre

    /** Falls back to idle: a pack that is missing a clip must not stop the fight. */
    fun clip(clip: HeroClip): Clip = clips[clip] ?: clips.getValue(HeroClip.IDLE)
}
